name: test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: npm
    - run: npm install -g eslint --ignore-scripts
    - run: npm ci --ignore-scripts
    - run: npm test
      env:
        CI: true
